# Generated by Django 2.2 on 2020-10-15 15:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SortType',
            fields=[
                ('sort_id', models.AutoField(primary_key=True, serialize=False)),
                ('sort_name', models.CharField(blank=True, max_length=30, verbose_name='分类名称')),
                ('sort_detail', models.CharField(blank=True, max_length=50, verbose_name='分类描述')),
                ('sort_image', models.ImageField(blank=True, default='sort_images/default.png', upload_to='sort_images/%Y/%m/%d', verbose_name='分类图⽚')),
                ('sort_level', models.IntegerField(verbose_name='分类级别')),
                ('show_flag', models.IntegerField(default=1, verbose_name='显示标记')),
                ('priority', models.IntegerField(default=0, verbose_name='显示优先级')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sorts.SortType', verbose_name='⽗级分类')),
            ],
            options={
                'verbose_name': '分类信息',
                'verbose_name_plural': '分类信息',
                'ordering': ('created_time',),
            },
        ),
    ]
