# Generated by Django 2.2 on 2020-10-15 16:56

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_detail',
            field=tinymce.models.HTMLField(blank=True, verbose_name='商品详情'),
        ),
    ]
